"""
Profile loader for Democratic Agents.

Profiles are generated by ai-gov-simulator's prompts (lib/prompts.js) and stored in
data/senate_profiles.json, data/executive_profiles.json, data/scotus_profiles.json.

Schema mirrors ai-gov-simulator exactly so vote_calculator can use the fields directly.
"""

from __future__ import annotations
import json
import os
from typing import Optional

# Path to profile data directory relative to this file
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data")

# Issue dimensions used across all legislative agents (matches ai-gov-simulator)
ISSUE_KEYS = [
    "immigration",
    "taxes_spending",
    "healthcare",
    "gun_rights",
    "climate_energy",
    "defense_military",
    "education",
    "tech_regulation",
    "criminal_justice",
    "trade_tariffs",
    "abortion_social",
    "government_spending",
    "foreign_policy_hawks",
    "civil_liberties",
    "labor_unions",
]

# Constitutional issue dimensions used for SCOTUS agents
CONSTITUTIONAL_ISSUE_KEYS = [
    "executive_power",
    "individual_rights_vs_government",
    "federal_vs_state_power",
    "regulatory_authority_admin_state",
    "criminal_defendant_rights",
    "free_speech_1A",
    "gun_rights_2A",
    "religious_liberty",
    "abortion_reproductive_rights",
    "commerce_clause_scope",
    "equal_protection_discrimination",
    "voting_rights",
    "immigration_executive_authority",
    "environmental_regulation",
]


class ProfileStore:
    """
    Loads and indexes agent profiles from JSON files in data/.

    Usage:
        store = ProfileStore()
        profile = store.get("Bernie Sanders")
        senate_10 = store.get_roster("senate", n=10)
    """

    def __init__(self, data_dir: str = DATA_DIR):
        self._data_dir = data_dir
        self._senate: dict[str, dict] = {}
        self._executive: dict[str, dict] = {}
        self._scotus: dict[str, dict] = {}
        self._load_all()

    def _load_all(self) -> None:
        # TODO: Generate these files by porting ai-gov-simulator's generation pipeline.
        #       Run: python src/heuristics/generate_profiles.py
        #       Which calls Anthropic API using SENATE_SYSTEM/SENATE_PROMPT from ai-gov-simulator.
        for fname, target in [
            ("senate_profiles.json", self._senate),
            ("executive_profiles.json", self._executive),
            ("scotus_profiles.json", self._scotus),
        ]:
            path = os.path.join(self._data_dir, fname)
            if os.path.exists(path):
                with open(path) as f:
                    profiles = json.load(f)
                for p in profiles:
                    if p.get("status") != "no_longer_serving":
                        target[p["name"]] = p
            # If file doesn't exist yet, the store is empty for that branch.
            # Call generate_profiles.py to populate.

    def get(self, name: str) -> Optional[dict]:
        """Return profile by exact name across all branches."""
        return (
            self._senate.get(name)
            or self._executive.get(name)
            or self._scotus.get(name)
        )

    def get_roster(self, chamber: str, n: Optional[int] = None) -> list[dict]:
        """
        Return a list of profiles for a chamber.

        chamber: "senate" | "executive" | "scotus"
        n: max number of agents (None = all). For senate, a balanced party subset
           is selected when n < total.

        TODO: For "senate", implement balanced selection — pick n/2 R + n/2 D (+ independents)
              sorted by seniority so the most prominent senators are included first.
        """
        store = {
            "senate": self._senate,
            "executive": self._executive,
            "scotus": self._scotus,
        }.get(chamber, {})

        profiles = list(store.values())

        if n is not None and len(profiles) > n:
            # TODO: Replace with balanced party selection for senate
            profiles = profiles[:n]

        return profiles

    def validate_profile(self, profile: dict, ptype: str) -> list[str]:
        """
        Validate a profile has the required fields for simulation.
        Returns list of warning strings (empty = valid).

        TODO: Mirror validate_profile() from ai-gov-simulator/lib/generate.js
        """
        warnings = []
        name = profile.get("name", "UNKNOWN")

        if ptype in ("senate", "executive"):
            if not profile.get("issues"):
                warnings.append(f"{name}: missing issues")
            else:
                vals = list(profile["issues"].values())
                if any(v < 0 or v > 1 for v in vals):
                    warnings.append(f"{name}: issue score out of range")
                if len(set(vals)) == 1:
                    warnings.append(f"{name}: all issue scores identical (likely bad generation)")
            if not profile.get("behavior"):
                warnings.append(f"{name}: missing behavior")
            if not profile.get("personality"):
                warnings.append(f"{name}: missing personality")

        if ptype == "scotus":
            if not profile.get("constitutional_issues"):
                warnings.append(f"{name}: missing constitutional_issues")
            if not profile.get("judicial_behavior"):
                warnings.append(f"{name}: missing judicial_behavior")

        if ptype == "executive":
            if not profile.get("veto_factors"):
                warnings.append(f"{name}: missing veto_factors")

        return warnings
