"""
Profile loader for Democratic Agents.

Profiles are loaded from ai-gov-simulator/data/government-profiles.json —
the single source of truth generated by the ai-gov-simulator project.

Schema mirrors ai-gov-simulator exactly so vote_calculator can use the fields directly.
"""

from __future__ import annotations
import json
import os
from pathlib import Path
from typing import Optional

# Single combined profiles file from ai-gov-simulator
PROFILES_FILE = Path(__file__).parent.parent.parent / "data" / "government-profiles.json"

# Issue dimensions used across all legislative agents (matches ai-gov-simulator)
ISSUE_KEYS = [
    "immigration",
    "taxes_spending",
    "healthcare",
    "gun_rights",
    "climate_energy",
    "defense_military",
    "education",
    "tech_regulation",
    "criminal_justice",
    "trade_tariffs",
    "abortion_social",
    "government_spending",
    "foreign_policy_hawks",
    "civil_liberties",
    "labor_unions",
]

# Constitutional issue dimensions used for SCOTUS agents
CONSTITUTIONAL_ISSUE_KEYS = [
    "executive_power",
    "individual_rights_vs_government",
    "federal_vs_state_power",
    "regulatory_authority_admin_state",
    "criminal_defendant_rights",
    "free_speech_1A",
    "gun_rights_2A",
    "religious_liberty",
    "abortion_reproductive_rights",
    "commerce_clause_scope",
    "equal_protection_discrimination",
    "voting_rights",
    "immigration_executive_authority",
    "environmental_regulation",
]


def _balanced_subset(profiles: list[dict], n: int) -> list[dict]:
    """
    Pick n profiles with balanced party representation.
    Takes floor(n/2) from each major party, fills remainder with independents/others.
    """
    r = [p for p in profiles if p.get("party") == "R"]
    d = [p for p in profiles if p.get("party") == "D"]
    other = [p for p in profiles if p.get("party") not in ("R", "D")]
    each = n // 2
    selected = r[:each] + d[:each]
    remaining = n - len(selected)
    selected += other[:remaining]
    # Pad from whichever party has more if still short
    if len(selected) < n:
        used = set(id(p) for p in selected)
        extras = [p for p in profiles if id(p) not in used]
        selected += extras[: n - len(selected)]
    return selected


class ProfileStore:
    """
    Loads and indexes agent profiles from ai-gov-simulator/data/government-profiles.json.

    Usage:
        store = ProfileStore()
        profile = store.get("Bernie Sanders")
        senate_10 = store.get_roster("senate", n=10)
    """

    def __init__(self, profiles_file: Path = PROFILES_FILE):
        self._profiles_file = profiles_file
        self._senate: dict[str, dict] = {}
        self._executive: dict[str, dict] = {}
        self._scotus: dict[str, dict] = {}
        self._house: dict[str, dict] = {}
        self._load_all()

    def _load_all(self) -> None:
        with open(self._profiles_file) as f:
            data = json.load(f)
        for chamber, target in [
            ("senate", self._senate),
            ("executive", self._executive),
            ("scotus", self._scotus),
            ("house", self._house),
        ]:
            for p in data.get(chamber, []):
                if p.get("status") != "no_longer_serving":
                    target[p["name"]] = p

    def get(self, name: str) -> Optional[dict]:
        """Return profile by exact name across all branches."""
        return (
            self._senate.get(name)
            or self._executive.get(name)
            or self._scotus.get(name)
            or self._house.get(name)
        )

    def get_roster(self, chamber: str, n: Optional[int] = None) -> list[dict]:
        """
        Return a list of profiles for a chamber.

        chamber: "senate" | "house" | "executive" | "scotus"
        n: max number of agents (None = all). For senate/house, picks a balanced
           party subset (n/2 R + n/2 D + independents) when n < total.

        TODO: Sort balanced subset by seniority so the most prominent members are first.
        """
        store = {
            "senate": self._senate,
            "executive": self._executive,
            "scotus": self._scotus,
            "house": self._house,
        }.get(chamber, {})

        profiles = list(store.values())

        if n is not None and len(profiles) > n:
            if chamber in ("senate", "house"):
                profiles = _balanced_subset(profiles, n)
            else:
                profiles = profiles[:n]

        return profiles

    def validate_profile(self, profile: dict, ptype: str) -> list[str]:
        """
        Validate a profile has the required fields for simulation.
        Returns list of warning strings (empty = valid).

        TODO: Mirror validate_profile() from ai-gov-simulator/lib/generate.js
        """
        warnings = []
        name = profile.get("name", "UNKNOWN")

        if ptype in ("senate", "executive"):
            if not profile.get("issues"):
                warnings.append(f"{name}: missing issues")
            else:
                vals = list(profile["issues"].values())
                if any(v < 0 or v > 1 for v in vals):
                    warnings.append(f"{name}: issue score out of range")
                if len(set(vals)) == 1:
                    warnings.append(f"{name}: all issue scores identical (likely bad generation)")
            if not profile.get("behavior"):
                warnings.append(f"{name}: missing behavior")
            if not profile.get("personality"):
                warnings.append(f"{name}: missing personality")

        if ptype == "scotus":
            if not profile.get("constitutional_issues"):
                warnings.append(f"{name}: missing constitutional_issues")
            if not profile.get("judicial_behavior"):
                warnings.append(f"{name}: missing judicial_behavior")

        if ptype == "executive":
            if not profile.get("veto_factors"):
                warnings.append(f"{name}: missing veto_factors")

        return warnings
